pipeline:
  build:
    image: node:9.2.0-alpine
    commands:
      - npm install
      - npm run test
  notify:
    image: plugins/slack
    channel: dev
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]